<template>
   <section class="relative w-full h-screen overflow-hidden -mt-[1px]">
    <img src="/images/check_konpvQ9.jpg" class="absolute insert-0 object-cover w-full h-full transition-all duration-700" alt="">
    <div class="relative z-20 flex items-center justify-start h-full px-6 md:px-24">
         <div class="space-y-6 max-w-3xl mt-16 text-left">
            <h2 class="text-xl md:text-2xl font-light text-white flex items-center" style="opacity: 1; transform:none;" >Caring with compasion</h2>
            <h1 class="text-3xl md:text-6xl font-extrabold text-white" style="opacity: 1; transform: none;"><span>shaping the future of care</span></h1>
            <p class="text-lg md:text-xl font-light text-white" style="opacity: 1; transform: none;">We provide professional training and services in elderly care, embracing diversity and dignity while preparing caregivers to succeed at home and abroad.</p>
            <div class="flex gap-4 pt-4" style="opacity: 1; transform: none;">
               <button class="bg-[#e7a98b] text-black font-semibold px-6 py-2 rounded-md hover:opacity-90 transition">Our Services</button>
               <button class="bg-white text-black font-semibold border border-gray-300  px-6 py-2 rounded-md hover:bg-black hover:text-white transition">About Us</button>
            </div>
         </div>
    </div>
   </section>
   
   <section class="relative px-6 md:px-20 py-12 bg-gradient-to-br from-gray-50 via-white to-gray-100 overflow-hidden">
      <div class="absolute inset-0 opacity-30">
      <div class="absolute top-20 left-10 w-32 h-32 bg-[#e7a98b] rounded-full blur-3xl"></div>
      <div class="absolute bottom-20 right-10 w-40 h-40 bg-[#e7a98b] rounded-full blur-3xl"></div>
      <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-60 h-60 bg-[#e7a98b] rounded-full blur-3xl"></div>
      </div>
      <div class="max-w-7xl mx-auto relative z-10">
         <div class="text-center mb-10">
            <h2 class="text-4xl md:text-5xl font-bold text-gray-800 mb-4">
               Our
               <span class="bg-[#e7a98b] bg-clip-text text-transparent">Services</span>
            </h2>
            <p class="text-gray-600 text-lg max-w-2xl mx-auto">Comprehensive care solutions designed to enhance quality of life and provide peace of mind</p>
         </div>
         <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8 items-stretch">
            <div class="group relative bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all duration-500 cursor-pointer transform hover:-translate-y-2 border border-gray-100 flex flex-col justify-between h-full" style="animation-delay: 0ms;"><div class="absolute inset-0 bg-amber-50 rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div><div class="relative z-10 flex flex-col h-full justify-between"><div><div class="relative mb-8"><div class="absolute inset-0 w-20 h-20 mx-auto"><div class="w-full h-full bg-gradient-to-r from-amber-500 to-orange-500 rounded-full opacity-20 animate-pulse"></div></div><div class="relative w-20 h-20 flex items-center justify-center bg-[#e7a98b] from-amber-500 to-orange-500 rounded-full shadow-lg mx-auto group-hover:scale-110 transition-transform duration-300"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-house text-white drop-shadow-sm" aria-hidden="true"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"></path><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg><div class="absolute -top-1 -right-1 w-3 h-3 bg-white rounded-full opacity-80 group-hover:animate-bounce"></div><div class="absolute -bottom-1 -left-1 w-2 h-2 bg-white rounded-full opacity-60 group-hover:animate-bounce" style="animation-delay: 0.5s;"></div></div></div><h3 class="text-xl font-bold text-gray-800 mb-4 text-center">Home Care</h3><p class="text-gray-600 text-sm leading-relaxed text-center mb-6">Training on assisting clients with daily living at home — ensuring safety, comfort, and dignity.</p></div><div class="flex justify-center"><button class="relative px-6 py-2 bg-[#e7a98b] text-white text-sm font-semibold rounded-full shadow-md hover:shadow-lg transform hover:scale-105 transition-all duration-300 overflow-hidden group/btn"><span class="relative z-10">Read more</span><div class="absolute inset-0 bg-gradient-to-r from-transparent via-white to-transparent opacity-0 group-hover/btn:opacity-20 transform -skew-x-12 group-hover/btn:translate-x-full transition-all duration-700"></div><svg class="inline-block ml-2 w-4 h-4 transform group-hover/btn:translate-x-1 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg></button></div></div><div class="absolute inset-0 rounded-3xl bg-gradient-to-r from-amber-500 to-orange-500 opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300 -z-10"></div></div>
            <div class="group relative bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all duration-500 cursor-pointer transform hover:-translate-y-2 border border-gray-100 flex flex-col justify-between h-full" style="animation-delay: 0ms;"><div class="absolute inset-0 bg-amber-50 rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div><div class="relative z-10 flex flex-col h-full justify-between"><div><div class="relative mb-8"><div class="absolute inset-0 w-20 h-20 mx-auto"><div class="w-full h-full bg-gradient-to-r from-amber-500 to-orange-500 rounded-full opacity-20 animate-pulse"></div></div><div class="relative w-20 h-20 flex items-center justify-center bg-[#e7a98b] from-amber-500 to-orange-500 rounded-full shadow-lg mx-auto group-hover:scale-110 transition-transform duration-300"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-house text-white drop-shadow-sm" aria-hidden="true"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"></path><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg><div class="absolute -top-1 -right-1 w-3 h-3 bg-white rounded-full opacity-80 group-hover:animate-bounce"></div><div class="absolute -bottom-1 -left-1 w-2 h-2 bg-white rounded-full opacity-60 group-hover:animate-bounce" style="animation-delay: 0.5s;"></div></div></div><h3 class="text-xl font-bold text-gray-800 mb-4 text-center">Home Care</h3><p class="text-gray-600 text-sm leading-relaxed text-center mb-6">Training on assisting clients with daily living at home — ensuring safety, comfort, and dignity.</p></div><div class="flex justify-center"><button class="relative px-6 py-2 bg-[#e7a98b] text-white text-sm font-semibold rounded-full shadow-md hover:shadow-lg transform hover:scale-105 transition-all duration-300 overflow-hidden group/btn"><span class="relative z-10">Read more</span><div class="absolute inset-0 bg-gradient-to-r from-transparent via-white to-transparent opacity-0 group-hover/btn:opacity-20 transform -skew-x-12 group-hover/btn:translate-x-full transition-all duration-700"></div><svg class="inline-block ml-2 w-4 h-4 transform group-hover/btn:translate-x-1 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg></button></div></div><div class="absolute inset-0 rounded-3xl bg-gradient-to-r from-amber-500 to-orange-500 opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300 -z-10"></div></div>
            <div class="group relative bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all duration-500 cursor-pointer transform hover:-translate-y-2 border border-gray-100 flex flex-col justify-between h-full" style="animation-delay: 0ms;"><div class="absolute inset-0 bg-amber-50 rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div><div class="relative z-10 flex flex-col h-full justify-between"><div><div class="relative mb-8"><div class="absolute inset-0 w-20 h-20 mx-auto"><div class="w-full h-full bg-gradient-to-r from-amber-500 to-orange-500 rounded-full opacity-20 animate-pulse"></div></div><div class="relative w-20 h-20 flex items-center justify-center bg-[#e7a98b] from-amber-500 to-orange-500 rounded-full shadow-lg mx-auto group-hover:scale-110 transition-transform duration-300"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-house text-white drop-shadow-sm" aria-hidden="true"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"></path><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg><div class="absolute -top-1 -right-1 w-3 h-3 bg-white rounded-full opacity-80 group-hover:animate-bounce"></div><div class="absolute -bottom-1 -left-1 w-2 h-2 bg-white rounded-full opacity-60 group-hover:animate-bounce" style="animation-delay: 0.5s;"></div></div></div><h3 class="text-xl font-bold text-gray-800 mb-4 text-center">Home Care</h3><p class="text-gray-600 text-sm leading-relaxed text-center mb-6">Training on assisting clients with daily living at home — ensuring safety, comfort, and dignity.</p></div><div class="flex justify-center"><button class="relative px-6 py-2 bg-[#e7a98b] text-white text-sm font-semibold rounded-full shadow-md hover:shadow-lg transform hover:scale-105 transition-all duration-300 overflow-hidden group/btn"><span class="relative z-10">Read more</span><div class="absolute inset-0 bg-gradient-to-r from-transparent via-white to-transparent opacity-0 group-hover/btn:opacity-20 transform -skew-x-12 group-hover/btn:translate-x-full transition-all duration-700"></div><svg class="inline-block ml-2 w-4 h-4 transform group-hover/btn:translate-x-1 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg></button></div></div><div class="absolute inset-0 rounded-3xl bg-gradient-to-r from-amber-500 to-orange-500 opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300 -z-10"></div></div>
            <div class="group relative bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all duration-500 cursor-pointer transform hover:-translate-y-2 border border-gray-100 flex flex-col justify-between h-full" style="animation-delay: 0ms;"><div class="absolute inset-0 bg-amber-50 rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div><div class="relative z-10 flex flex-col h-full justify-between"><div><div class="relative mb-8"><div class="absolute inset-0 w-20 h-20 mx-auto"><div class="w-full h-full bg-gradient-to-r from-amber-500 to-orange-500 rounded-full opacity-20 animate-pulse"></div></div><div class="relative w-20 h-20 flex items-center justify-center bg-[#e7a98b] from-amber-500 to-orange-500 rounded-full shadow-lg mx-auto group-hover:scale-110 transition-transform duration-300"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-house text-white drop-shadow-sm" aria-hidden="true"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"></path><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg><div class="absolute -top-1 -right-1 w-3 h-3 bg-white rounded-full opacity-80 group-hover:animate-bounce"></div><div class="absolute -bottom-1 -left-1 w-2 h-2 bg-white rounded-full opacity-60 group-hover:animate-bounce" style="animation-delay: 0.5s;"></div></div></div><h3 class="text-xl font-bold text-gray-800 mb-4 text-center">Home Care</h3><p class="text-gray-600 text-sm leading-relaxed text-center mb-6">Training on assisting clients with daily living at home — ensuring safety, comfort, and dignity.</p></div><div class="flex justify-center"><button class="relative px-6 py-2 bg-[#e7a98b] text-white text-sm font-semibold rounded-full shadow-md hover:shadow-lg transform hover:scale-105 transition-all duration-300 overflow-hidden group/btn"><span class="relative z-10">Read more</span><div class="absolute inset-0 bg-gradient-to-r from-transparent via-white to-transparent opacity-0 group-hover/btn:opacity-20 transform -skew-x-12 group-hover/btn:translate-x-full transition-all duration-700"></div><svg class="inline-block ml-2 w-4 h-4 transform group-hover/btn:translate-x-1 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg></button></div></div><div class="absolute inset-0 rounded-3xl bg-gradient-to-r from-amber-500 to-orange-500 opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300 -z-10"></div></div>
         </div>
      </div>
   </section>
</template>